### ISSUE TITLE
The method 'contains' was called on null - Quando Auth está ativo

### ISSUE THREAD

**Issue by moaberdan** [Flutterando/dartio#4]
Fala Jacob, blz?

Estava testando seu pacote e encontrei um pequeno bug, segue:

Quando ativado a funcionalidade de autenticação e a propriedade "scape" não está ativa ou não possui nenhuma definição de rota a seguinte exceção está sendo apresentada: *The method 'contains' was called on null* 

Segue um print com mais informações do erro.

![Captura de Tela_Área de Seleção_20200427145941](https://user-images.githubusercontent.com/4240026/80405598-3643ac80-8899-11ea-8dbc-0592f75ddf17.png)

Isto provavelmente esta acontecendo porque na classe AuthService a variável "scape" não esta sendo inicializada. No método "isValid()", está sendo verificado as rotas excluídas da proteção do token("scape.contains(route)"), mas para esse caso mencionado a variável estará nula, resultando na exceção "NoSuchMethodError".

**Comment by jacobaraujo7** [comment]
Obrigadão! Corrigindo!
